default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: "db/development.sqlite3"

test:
  <<: *default
  database: "db/test.sqlite3"

production:
  <<: *default
  database: dbdeln9psr3cah
  username: rydljwkvcocdkz
  host: ec2-52-207-90-231.compute-1.amazonaws.com
  password: d2f268c03a31239afef9f9b6be0f67f7c204495accb36cb9f472462016e0020f