default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: "db/development.sqlite3"

test:
  <<: *default
  database: "db/test.sqlite3"

production:
  <<: *default
  database: dbpeu03bl95ubv
  username: eahrscyajcqpoe
  host: ec2-44-209-158-64.compute-1.amazonaws.com
  password: 43c6121818e2f0ee16214f6e966128e2a9bb52134558debe54a97912ca5f0227